version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: wirw-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    build: ./backend
    container_name: wirw-backend
    environment:
      DB_HOST: db
      DB_USER: wirw-user
      DB_PASSWORD: password
      DB_NAME: wirw-db
      DB_PORT: 5432
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules

  db:
    image: postgres:15-alpine3.17
    container_name: wirw-db
    environment:
      POSTGRES_USER: wirw-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wirw-db
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend_node_modules:
  backend_node_modules: